import React, { useRef, useState } from 'react';
import { Student } from '../types';
import logo from '../assets/images/kssb_fc_official_logo.jpg';
import { X, ShieldCheck, Sparkles, CheckCircle2, QrCode, User, ArrowLeft, Download, Smartphone, Loader2 } from 'lucide-react';
import { calculateExactAge, formatDateToDDMMYYYY } from '../utils/dateUtils';
import html2canvas from 'html2canvas';

interface PlayerIDCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  student: Student | null;
  autoGeneratedNotice?: boolean;
}

export default function PlayerIDCardModal({
  isOpen,
  onClose,
  student,
  autoGeneratedNotice = false
}: PlayerIDCardModalProps) {
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccessMsg, setSaveSuccessMsg] = useState<string | null>(null);
  const cardRef = useRef<HTMLDivElement | null>(null);

  if (!isOpen || !student) return null;

  const ageData = calculateExactAge(student.dob, student.age);
  const calculatedYears = ageData.years;

  const handleSaveJpeg = async () => {
    if (!cardRef.current || isSaving) return;
    setIsSaving(true);
    setSaveSuccessMsg(null);

    try {
      // High-resolution capture at 3x scale for crisp, standard ID card JPEG output
      const canvas = await html2canvas(cardRef.current, {
        scale: 3,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#052e16', // Deep emerald background
        logging: false,
      });

      const safeRegNo = (student.registrationNumber || 'ID_CARD').replace(/[^a-zA-Z0-9]/g, '_');
      const fileName = `KSSB_FC_ID_Card_${student.name.replace(/\s+/g, '_')}_${safeRegNo}.jpg`;
      const jpegDataUrl = canvas.toDataURL('image/jpeg', 0.95);

      // Attempt Web Share API for Mobile Devices (directly saves/shares JPEG to mobile Photos/Gallery)
      canvas.toBlob(async (blob) => {
        let sharedSuccessfully = false;
        if (blob) {
          const file = new File([blob], fileName, { type: 'image/jpeg' });
          if (navigator.canShare && navigator.canShare({ files: [file] })) {
            try {
              await navigator.share({
                files: [file],
                title: `${student.name} - KSSB FC Player ID Card`,
                text: `Official KSSB FC Player ID Card for ${student.name}`,
              });
              sharedSuccessfully = true;
            } catch {
              // User dismissed native share sheet; fallback to direct download link below
            }
          }
        }

        if (!sharedSuccessfully) {
          const link = document.createElement('a');
          link.download = fileName;
          link.href = jpegDataUrl;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
        }

        setIsSaving(false);
        setSaveSuccessMsg('✅ High Resolution ID Card saved in JPEG format!');
        setTimeout(() => setSaveSuccessMsg(null), 4000);
      }, 'image/jpeg', 0.95);

    } catch (err) {
      console.error('Failed to generate JPEG ID card:', err);
      setIsSaving(false);
      alert('Could not save ID Card image. Please try again.');
    }
  };

  return (
    <div className="fixed inset-0 bg-black/75 backdrop-blur-md z-50 flex items-center justify-center p-3 sm:p-4 overflow-y-auto transition-all" id="id-card-modal-backdrop">
      <div className="bg-white rounded-3xl max-w-md w-full p-4 sm:p-6 space-y-4 shadow-2xl relative border border-emerald-100 my-auto">
        
        {/* Header Action Controls */}
        <div className="flex items-center justify-between pb-3 border-b border-gray-100">
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer border border-slate-200"
              id="id-card-top-back-btn"
            >
              <ArrowLeft size={14} /> Back
            </button>
            <div>
              <h3 className="text-base font-black text-gray-900 leading-none">Official Player ID Card</h3>
              <span className="text-[10px] font-mono font-bold text-gray-400 uppercase tracking-wider">KSSB FC Identity Pass</span>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="px-3 py-1.5 bg-rose-50 text-rose-700 hover:bg-rose-100 rounded-xl text-xs font-bold flex items-center gap-1 transition-all cursor-pointer border border-rose-200"
            title="Close ID Card"
            id="id-card-top-close-btn"
          >
            <X size={16} /> Close
          </button>
        </div>

        {/* Auto Generated Success Notice */}
        {autoGeneratedNotice && (
          <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-3 flex items-start gap-2.5 text-emerald-900 animate-fade-in">
            <CheckCircle2 size={18} className="text-emerald-600 shrink-0 mt-0.5" />
            <div className="text-xs">
              <div className="font-bold text-emerald-950 flex items-center gap-1">
                Registration Complete! <Sparkles size={14} className="text-amber-500" />
              </div>
              <p className="mt-0.5 text-emerald-800 leading-snug">
                Official Player ID Card generated for <strong>{student.name}</strong>.
              </p>
            </div>
          </div>
        )}

        {/* Save Confirmation Banner */}
        {saveSuccessMsg && (
          <div className="bg-amber-50 border border-amber-300 rounded-2xl p-2.5 text-xs font-bold text-amber-900 text-center animate-fade-in flex items-center justify-center gap-2">
            <Smartphone size={16} className="text-amber-600" />
            <span>{saveSuccessMsg}</span>
          </div>
        )}

        {/* ID Card Graphic Canvas (Ref targeted for html2canvas high-res export) */}
        <div 
          ref={cardRef} 
          className="bg-gradient-to-br from-emerald-950 via-slate-900 to-emerald-900 rounded-2xl p-4 sm:p-5 text-white shadow-xl relative overflow-hidden border-2 border-amber-400/90 space-y-3.5 w-full select-none" 
          id="printable-player-id-card"
        >
          {/* Background Watermark Crest */}
          <div className="absolute right-[-20px] bottom-[-20px] opacity-10 pointer-events-none">
            <img src={logo || '/logo.jpg'} alt="Watermark" className="w-64 h-64 object-contain" />
          </div>

          {/* ID Card Top Header */}
          <div className="flex items-center justify-between gap-3 pb-3 border-b border-emerald-700/60 relative z-10">
            <div className="flex items-center gap-2.5">
              <img 
                src={logo || '/logo.jpg'} 
                onError={(e) => {
                  const img = e.currentTarget as HTMLImageElement;
                  img.onerror = null;
                  img.src = '/logo.jpg';
                }}
                alt="KSSB FC Crest" 
                className="w-11 h-11 rounded-xl border-2 border-amber-400 object-cover bg-slate-900 shadow-md shrink-0"
                referrerPolicy="no-referrer"
              />
              <div>
                <span className="text-[8.5px] font-mono font-bold text-amber-300 uppercase tracking-widest block leading-none">
                  KADAMTALA SPORTING
                </span>
                <h4 className="text-xs sm:text-sm font-black font-sans tracking-tight text-white leading-tight">
                  SUBHAS BHOWMICK FOOTBALL CAMP
                </h4>
                <span className="text-[8px] font-mono text-emerald-300 uppercase tracking-wider block mt-0.5">
                  Official Athlete Pass • Session 2026-27
                </span>
              </div>
            </div>
          </div>

          {/* ID Card Content Body */}
          <div className="grid grid-cols-12 gap-3 items-center relative z-10">
            
            {/* Player Captured Camera Photo / Avatar */}
            <div className="col-span-5 flex flex-col items-center justify-center">
              <div className="w-26 h-30 sm:w-28 sm:h-34 rounded-xl border-2 border-amber-400 overflow-hidden bg-slate-900 shadow-lg relative flex items-center justify-center">
                <img 
                  src={student.photoUrl && student.photoUrl.trim() !== '' ? student.photoUrl : (logo || '/logo.jpg')} 
                  alt={student.name} 
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    const img = e.currentTarget as HTMLImageElement;
                    img.onerror = null;
                    img.src = '/logo.jpg';
                  }}
                />
              </div>
              <span className="text-[8.5px] font-mono text-amber-300 font-bold mt-1 uppercase tracking-wider text-center">
                U-{calculatedYears <= 12 ? '12' : calculatedYears <= 15 ? '15' : calculatedYears <= 18 ? '18' : '21'} Category
              </span>
            </div>

            {/* Player Details Breakdown */}
            <div className="col-span-7 space-y-1.5 text-left">
              <div className="border-b border-emerald-800/60 pb-1">
                <span className="text-[8px] font-mono text-emerald-300 uppercase tracking-wider block font-bold">Player Name</span>
                <h3 className="text-sm font-black text-white font-sans leading-tight drop-shadow-xs truncate">
                  {student.name}
                </h3>
              </div>

              {/* Registration Number */}
              <div>
                <span className="text-[8px] font-mono text-emerald-300 uppercase tracking-wider block font-bold">Reg. Number</span>
                <span className="inline-block bg-amber-400/20 text-amber-300 border border-amber-400/40 px-2 py-0.5 rounded font-mono font-extrabold text-[10px] leading-none tracking-wide">
                  {student.registrationNumber || 'KSSBFC0001/26-27'}
                </span>
              </div>

              {/* Reg Date & Playing Position */}
              <div className="grid grid-cols-2 gap-1.5 text-[10px]">
                <div>
                  <span className="text-[8px] font-mono text-amber-300 uppercase tracking-wider block font-bold">Reg. Date</span>
                  <span className="inline-block text-white font-mono font-bold text-[10px] leading-none mt-0.5">
                    {formatDateToDDMMYYYY(student.registrationDate)}
                  </span>
                </div>
                <div>
                  <span className="text-[8px] font-mono text-emerald-300 uppercase tracking-wider block font-bold">Playing Position</span>
                  <span className="inline-block bg-amber-400/30 text-amber-200 border border-amber-400/60 px-1.5 py-0.5 rounded font-black text-[10px] uppercase tracking-wide leading-none">
                    {student.position}
                  </span>
                </div>
              </div>

              {/* Player Age & Date of Birth */}
              <div className="grid grid-cols-2 gap-1.5 text-[10px]">
                <div>
                  <span className="text-[8px] font-mono text-emerald-300 uppercase tracking-wider block font-bold">Player Age</span>
                  <span className="inline-block bg-emerald-500/20 text-emerald-200 border border-emerald-400/50 px-1.5 py-0.5 rounded font-mono font-extrabold text-[10px] leading-none">
                    {ageData.displayText}
                  </span>
                </div>
                <div>
                  <span className="text-[8px] font-mono text-slate-400 uppercase block font-bold">Date of Birth</span>
                  <span className="font-mono font-bold text-emerald-300 truncate block text-[10px] leading-tight">
                    {student.dob ? formatDateToDDMMYYYY(student.dob) : 'N/A'}
                  </span>
                </div>
              </div>

              {/* Father / Guardian & Mobile No */}
              <div className="grid grid-cols-2 gap-1.5 text-[10px]">
                <div>
                  <span className="text-[8px] font-mono text-slate-400 uppercase block font-bold">Father / Guardian</span>
                  <span className="font-bold text-slate-100 truncate block text-[10px] leading-tight">{student.fatherName || student.guardianName || '—'}</span>
                </div>
                <div>
                  <span className="text-[8px] font-mono text-slate-400 uppercase block font-bold">Mobile No</span>
                  <span className="font-mono font-bold text-emerald-300 truncate block text-[10px] leading-tight">{student.mobileNo || student.parentPhone || '—'}</span>
                </div>
              </div>

              {/* Aadhar / Age Category & Address */}
              <div className="grid grid-cols-2 gap-1.5 text-[10px]">
                {student.aadharNumber ? (
                  <div>
                    <span className="text-[8px] font-mono text-slate-400 uppercase block font-bold">
                      {student.isGuardianAadhar ? "Guardian Aadhar" : "Aadhar No"}
                    </span>
                    <span className="text-[9px] font-mono font-bold text-amber-300 block leading-tight">
                      {student.aadharNumber}
                    </span>
                  </div>
                ) : (
                  <div>
                    <span className="text-[8px] font-mono text-slate-400 uppercase block font-bold">Age Category</span>
                    <span className="text-[9px] font-mono font-bold text-amber-300 block leading-tight">
                      U-{calculatedYears <= 12 ? '12' : calculatedYears <= 15 ? '15' : calculatedYears <= 18 ? '18' : '21'}
                    </span>
                  </div>
                )}
                <div>
                  <span className="text-[8px] font-mono text-slate-400 uppercase block font-bold">Address</span>
                  <span className="text-[9px] text-slate-200 line-clamp-1 block leading-tight font-medium">{student.address || 'Kadam Tala, West Bengal'}</span>
                </div>
              </div>

            </div>

          </div>

          {/* ID Card Footer with QR Verification & Signature */}
          <div className="pt-2 border-t border-emerald-800/80 flex items-center justify-between text-[9px] relative z-10">
            <div className="flex items-center gap-2">
              <div className="p-1 bg-white rounded border border-amber-400 text-slate-900">
                <QrCode size={22} />
              </div>
              <div className="text-[8px] font-mono text-emerald-200">
                <div>Scan for Verification</div>
                <div className="text-[7px] text-slate-400">Valid Till: March 2027</div>
              </div>
            </div>

            <div className="text-right space-y-0.5">
              <div className="text-[9px] font-serif italic font-bold text-amber-300">A. Faniyan</div>
              <div className="text-[7px] font-mono text-slate-400 uppercase tracking-wider">Authorized Coach Seal</div>
            </div>
          </div>

        </div>

        {/* Modal Bottom Actions - Save JPEG Button Prominently Positioned */}
        <div className="flex flex-col sm:flex-row gap-2.5 pt-2 justify-between items-center">
          <button
            type="button"
            onClick={onClose}
            className="w-full sm:w-auto px-4 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 cursor-pointer transition-all border border-slate-200"
            id="id-card-footer-back-btn"
          >
            <ArrowLeft size={16} /> Back
          </button>
          
          <button
            type="button"
            onClick={handleSaveJpeg}
            disabled={isSaving}
            className="w-full sm:w-1/2 px-4 py-2.5 bg-emerald-700 hover:bg-emerald-800 disabled:bg-emerald-400 text-white rounded-xl text-xs font-extrabold shadow-md flex items-center justify-center gap-2 transition-all cursor-pointer active:scale-95"
            id="id-card-footer-save-btn"
          >
            {isSaving ? (
              <>
                <Loader2 size={16} className="animate-spin" />
                <span>Generating High-Res JPEG...</span>
              </>
            ) : (
              <>
                <Download size={16} />
                <span>Save ID Card (JPEG)</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={onClose}
            className="w-full sm:w-auto px-4 py-2.5 bg-rose-600 hover:bg-rose-700 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 transition-all cursor-pointer shadow-sm"
            id="id-card-footer-close-btn"
          >
            <X size={16} /> Close
          </button>
        </div>

      </div>
    </div>
  );
}
