import React from 'react';
import { Student } from '../types';
import logo from '../assets/images/kssb_fc_official_logo.jpg';
import { X, Printer, ShieldCheck, Sparkles, CheckCircle2, QrCode, User } from 'lucide-react';

interface PlayerIDCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  student: Student | null;
  autoGeneratedNotice?: boolean;
}

export default function PlayerIDCardModal({
  isOpen,
  onClose,
  student,
  autoGeneratedNotice = false
}: PlayerIDCardModalProps) {
  if (!isOpen || !student) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-md z-50 flex items-center justify-center p-3 sm:p-4 overflow-y-auto transition-all" id="id-card-modal-backdrop">
      <div className="bg-white rounded-3xl max-w-md w-full p-5 sm:p-6 space-y-5 shadow-2xl relative border border-emerald-100 my-auto print:shadow-none print:border-none print:p-0">
        
        {/* Header Action Controls - Hidden when printing */}
        <div className="flex items-center justify-between pb-3 border-b border-gray-100 print:hidden">
          <div className="flex items-center gap-2">
            <ShieldCheck size={20} className="text-emerald-600 shrink-0" />
            <div>
              <h3 className="text-base font-black text-gray-900 leading-none">Official Player ID Card</h3>
              <span className="text-[10px] font-mono font-bold text-gray-400 uppercase tracking-wider">KSSB FC Identity Pass</span>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-1.5 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-full cursor-pointer transition-colors"
            title="Close ID Card"
          >
            <X size={20} />
          </button>
        </div>

        {/* Auto Generated Success Notice */}
        {autoGeneratedNotice && (
          <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-3.5 flex items-start gap-3 text-emerald-900 print:hidden animate-fade-in">
            <CheckCircle2 size={20} className="text-emerald-600 shrink-0 mt-0.5" />
            <div className="text-xs">
              <div className="font-bold text-emerald-950 flex items-center gap-1">
                Registration Complete! <Sparkles size={14} className="text-amber-500" />
              </div>
              <p className="mt-0.5 text-emerald-800 leading-snug">
                Official Player ID Card has been automatically generated for <strong>{student.name}</strong>.
              </p>
            </div>
          </div>
        )}

        {/* Printable ID Card Graphic Canvas */}
        <div className="bg-gradient-to-br from-emerald-950 via-slate-900 to-emerald-900 rounded-2xl p-5 text-white shadow-xl relative overflow-hidden border-2 border-amber-400/80 space-y-4 print:m-0 print:w-full" id="printable-player-id-card">
          
          {/* Subtle Background Watermark / Pattern */}
          <div className="absolute right-[-20px] bottom-[-20px] opacity-10 pointer-events-none select-none">
            <img src={logo || '/logo.jpg'} alt="Watermark" className="w-64 h-64 object-contain" />
          </div>

          {/* ID Card Top Header */}
          <div className="flex items-center justify-between gap-3 pb-3 border-b border-emerald-700/60 relative z-10">
            <div className="flex items-center gap-2.5">
              <img 
                src={logo || '/logo.jpg'} 
                onError={(e) => {
                  const img = e.currentTarget as HTMLImageElement;
                  img.onerror = null;
                  img.src = '/logo.jpg';
                }}
                alt="KSSB FC Crest" 
                className="w-12 h-12 rounded-xl border-2 border-amber-400 object-cover bg-slate-900 shadow-md shrink-0"
                referrerPolicy="no-referrer"
              />
              <div>
                <span className="text-[9px] font-mono font-bold text-amber-300 uppercase tracking-widest block leading-none">
                  KADAMTALA SPORTING
                </span>
                <h4 className="text-sm font-black font-sans tracking-tight text-white leading-tight">
                  SUBHAS BHOWMICK FOOTBALL CAMP
                </h4>
                <span className="text-[8px] font-mono text-emerald-300 uppercase tracking-wider block mt-0.5">
                  Official Athlete Pass • Session 2026-27
                </span>
              </div>
            </div>
          </div>

          {/* ID Card Content Body */}
          <div className="grid grid-cols-12 gap-3.5 items-center relative z-10">
            
            {/* Player Captured Camera Photo / Avatar */}
            <div className="col-span-5 flex flex-col items-center">
              <div className="w-28 h-32 sm:w-32 sm:h-36 rounded-xl border-2 border-amber-400 overflow-hidden bg-slate-800 shadow-lg relative flex items-center justify-center group">
                <img 
                  src={student.photoUrl && student.photoUrl.trim() !== '' ? student.photoUrl : (logo || '/logo.jpg')} 
                  alt={student.name} 
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    const img = e.currentTarget as HTMLImageElement;
                    img.onerror = null;
                    img.src = '/logo.jpg';
                  }}
                />
                {/* Position Overlay Badge */}
                <span className="absolute bottom-1 right-1 bg-amber-500 text-slate-950 font-black text-[9px] px-1.5 py-0.5 rounded uppercase shadow-sm">
                  {student.position}
                </span>
              </div>
              <span className="text-[9px] font-mono text-amber-300 font-bold mt-1.5 uppercase tracking-wider text-center">
                U-{student.age <= 12 ? '12' : student.age <= 15 ? '15' : student.age <= 18 ? '18' : '21'} Category
              </span>
            </div>

            {/* Player Details Breakdown */}
            <div className="col-span-7 space-y-2 text-left">
              <div>
                <span className="text-[9px] font-mono text-emerald-300 uppercase tracking-wider block">Player Name</span>
                <h3 className="text-base sm:text-lg font-black text-white font-sans leading-tight drop-shadow-sm">
                  {student.name}
                </h3>
              </div>

              <div>
                <span className="text-[9px] font-mono text-emerald-300 uppercase tracking-wider block">Registration Number</span>
                <span className="inline-block bg-amber-400/20 text-amber-300 border border-amber-400/40 px-2 py-0.5 rounded font-mono font-extrabold text-xs">
                  {student.registrationNumber || 'KSSBFC0001/26-27'}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-1.5 text-[10px]">
                <div>
                  <span className="text-[8px] font-mono text-slate-400 uppercase block">Father / Guardian</span>
                  <span className="font-bold text-slate-100 truncate block">{student.fatherName || student.guardianName || '—'}</span>
                </div>
                <div>
                  <span className="text-[8px] font-mono text-slate-400 uppercase block">Mobile No</span>
                  <span className="font-mono font-bold text-emerald-300 truncate block">{student.mobileNo || student.parentPhone || '—'}</span>
                </div>
              </div>

              <div>
                <span className="text-[8px] font-mono text-slate-400 uppercase block">Address</span>
                <span className="text-[9px] text-slate-300 line-clamp-1 block leading-tight">{student.address || 'Kadam Tala, West Bengal'}</span>
              </div>
            </div>

          </div>

          {/* ID Card Footer with QR Verification & Signature */}
          <div className="pt-2.5 border-t border-emerald-800/80 flex items-center justify-between text-[9px] relative z-10">
            <div className="flex items-center gap-2">
              <div className="p-1 bg-white rounded border border-amber-400 text-slate-900">
                <QrCode size={24} />
              </div>
              <div className="text-[8px] font-mono text-emerald-200">
                <div>Scan for Verification</div>
                <div className="text-[7px] text-slate-400">Valid Till: March 2027</div>
              </div>
            </div>

            <div className="text-right space-y-0.5">
              <div className="text-[9px] font-serif italic font-bold text-amber-300">A. Faniyan</div>
              <div className="text-[7px] font-mono text-slate-400 uppercase tracking-wider">Authorized Coach Seal</div>
            </div>
          </div>

        </div>

        {/* Modal Bottom Actions - Hidden when printing */}
        <div className="flex flex-col sm:flex-row gap-2.5 pt-2 print:hidden">
          <button
            type="button"
            onClick={handlePrint}
            className="flex-1 py-2.5 bg-emerald-700 hover:bg-emerald-800 text-white rounded-xl text-xs font-bold shadow-md flex items-center justify-center gap-2 transition-all cursor-pointer"
          >
            <Printer size={16} />
            <span>Print / Save ID Card</span>
          </button>
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2.5 border border-gray-200 rounded-xl text-xs font-bold text-gray-700 hover:bg-gray-50 transition-all cursor-pointer text-center"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
}
